FROM node:22.15.0 AS build
WORKDIR /frontend
ARG VITE_API_URL=http://localhost
ENV VITE_API_URL=${VITE_API_URL}
COPY . .
RUN yarn install && yarn build

FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /frontend/dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

