version: '3.8'

services:
  vibe-trading-agent:
    labels:
      # These labels ensure that API routes get correctly proxied
      - "traefik.enable=true"
      - "traefik.http.routers.vibe-trading-api.rule=Host(`dev.thevibe.trading`) && PathPrefix(`/api`)"
      - "traefik.http.routers.vibe-trading-api.entrypoints=https"
      - "traefik.http.routers.vibe-trading-api.tls=true"
      - "traefik.http.routers.vibe-trading-api.tls.certresolver=forge"
      - "traefik.http.services.vibe-trading-api.loadbalancer.server.port=8000"
      # Health check endpoint
      - "traefik.http.routers.vibe-trading-health.rule=Host(`dev.thevibe.trading`) && Path(`/health`)"
      - "traefik.http.routers.vibe-trading-health.entrypoints=https"
      - "traefik.http.routers.vibe-trading-health.tls=true"
      - "traefik.http.routers.vibe-trading-health.tls.certresolver=forge"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibe-trading-agent
    # No need to expose port since Traefik will proxy requests
    # ports:
    #  - "127.0.0.1:8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DB_PATH=/app/data/emails.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - traefik_proxy
      
  vibe-trading-frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vibe-trading-frontend.rule=Host(`thevibe.trading`)"
      - "traefik.http.routers.vibe-trading-frontend.entrypoints=https"
      - "traefik.http.routers.vibe-trading-frontend.tls=true"
      - "traefik.http.routers.vibe-trading-frontend.tls.certresolver=forge"
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    container_name: vibe-trading-frontend
    depends_on:
      - vibe-trading-agent
    restart: unless-stopped
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
